const { OpenAI } = require('openai');
const dotenv = require('dotenv');

dotenv.config();

let openai = null;
if (process.env.OPENAI_API_KEY) {
  openai = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY,
  });
}

/**
 * High-quality fallback classifier using heuristics when OpenAI is unavailable.
 */
const runFallbackHeuristic = (title, description = '') => {
  const content = `${title.toLowerCase()} ${description.toLowerCase()}`;
  
  let category = 'Work';
  let priority = 'Medium';
  let summary = `Task regarding "${title}"`;

  // Determine Category
  if (content.includes('meeting') || content.includes('call') || content.includes('discuss') || content.includes('zoom')) {
    category = 'Meeting';
  } else if (content.includes('personal') || content.includes('buy') || content.includes('shop') || content.includes('family') || content.includes('vacation')) {
    category = 'Personal';
  } else if (content.includes('urgent') || content.includes('asap') || content.includes('fire') || content.includes('emergency')) {
    category = 'Urgent';
  } else {
    category = 'Work';
  }

  // Determine Priority
  if (content.includes('urgent') || content.includes('critical') || content.includes('blocker') || content.includes('immediate')) {
    priority = 'Critical';
  } else if (content.includes('high') || content.includes('important') || content.includes('asap') || content.includes('deadline')) {
    priority = 'High';
  } else if (content.includes('low') || content.includes('relax') || content.includes('whenever') || content.includes('backlog')) {
    priority = 'Low';
  } else {
    priority = 'Medium';
  }

  // Build a smart one-line summary
  if (description) {
    const cleanDesc = description.replace(/[\r\n]+/g, ' ').substring(0, 80);
    summary = `Title: ${title} - Details: ${cleanDesc}${description.length > 80 ? '...' : ''}`;
  } else {
    summary = `Keep track of: "${title}" (No description provided).`;
  }

  return {
    category,
    priority,
    aiGeneratedSummary: `[Mock AI] ${summary}`,
  };
};

/**
 * Main AI suggestion logic.
 * Analyzes title and description to predict category, priority, and summary.
 */
const getAiTaskSuggestions = async (title, description = '') => {
  if (!openai) {
    console.log('OpenAI API key missing. Using smart fallback heuristic...');
    return runFallbackHeuristic(title, description);
  }

  try {
    const prompt = `
Analyze this task and respond ONLY with a valid JSON object matching this schema:
{
  "category": "Work" | "Personal" | "Urgent" | "Meeting" | "Other",
  "priority": "Low" | "Medium" | "High" | "Critical",
  "summary": "a brief, one-line summary of the task"
}

Task Details:
Title: ${title}
Description: ${description}

Strict Rule: Return ONLY JSON, no markdown formatting like \`\`\`json\`\`\`, no extra conversational text.
`;

    const response = await openai.chat.completions.create({
      model: 'gpt-3.5-turbo',
      messages: [{ role: 'user', content: prompt }],
      temperature: 0.2,
      max_tokens: 200,
    });

    const resultText = response.choices[0].message.content.trim();
    
    // Parse response
    let suggestions;
    try {
      // Clean up markdown block wrapper just in case
      const cleanedJson = resultText.replace(/```json/g, '').replace(/```/g, '').trim();
      suggestions = JSON.parse(cleanedJson);
    } catch (e) {
      console.warn('AI returned invalid JSON, utilizing regex fallback parsing...', resultText);
      // Attempt manual extraction
      const categoryMatch = resultText.match(/"category"\s*:\s*"([^"]+)"/);
      const priorityMatch = resultText.match(/"priority"\s*:\s*"([^"]+)"/);
      const summaryMatch = resultText.match(/"summary"\s*:\s*"([^"]+)"/);

      suggestions = {
        category: categoryMatch ? categoryMatch[1] : 'Work',
        priority: priorityMatch ? priorityMatch[1] : 'Medium',
        summary: summaryMatch ? summaryMatch[1] : 'AI suggestion parsed via regex fallback.',
      };
    }

    // Validate enums
    const validCategories = ['Work', 'Personal', 'Urgent', 'Meeting', 'Other'];
    const validPriorities = ['Low', 'Medium', 'High', 'Critical'];

    return {
      category: validCategories.includes(suggestions.category) ? suggestions.category : 'Other',
      priority: validPriorities.includes(suggestions.priority) ? suggestions.priority : 'Medium',
      aiGeneratedSummary: suggestions.summary || 'Summary generated by AI.',
    };

  } catch (error) {
    console.error('OpenAI API call failed:', error.message);
    console.log('Falling back to local heuristic analysis...');
    return runFallbackHeuristic(title, description);
  }
};

module.exports = { getAiTaskSuggestions };
